name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download actionlint
        run: |
          mkdir -p "$HOME/bin"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) latest "$HOME/bin"
          echo "${HOME}/bin" >> "$GITHUB_PATH"
      - uses: open-turo/action-pre-commit@v1
