name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Download actionlint
        run: |
          mkdir -p "$HOME/bin"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) latest "$HOME/bin"
          echo "${HOME}/bin" >> "$GITHUB_PATH"
      - uses: open-turo/actions-node/lint@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-node/test@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-flags: --coverage
      - name: Upload coverage
        if: ${{ env.COVERALLS_REPO_TOKEN != '' }}
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
