name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup tools
        uses: open-turo/action-setup-tools@v1
      - name: Pre-commit
        uses: open-turo/action-pre-commit@v1
