name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
      - uses: actions/setup-python@v2
      - uses: KeisukeYamashita/setup-release@v1.0.2
        with:
          repository: rhysd/actionlint
      - uses: pre-commit/action@v2.0.0
