name: Release

on:
  push:
    branches: [main, "[0-9]+.x"]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-node/release@f/use_latest_semantic_release_action
        with:
          github-token: ${{ secrets.OPEN_TURO_GITHUB_TOKEN }}
          npm-token: ${{ secrets.OPEN_TURO_NPM_TOKEN }}
          extra-plugins: |
            @open-turo/semantic-release-config@8.0.0-pr-192.184.1.1
